### ISSUE TITLE
All OS Name List 

### ISSUE THREAD

**Issue by zeko2010ss** [FirstHeberg/api#1]
Where to get all OS name list ex: debian7-64

**Comment by GuillaumeJeanFrancois** [comment]
Hello,

You can retrieve the list of OS available for your VPS directly from the API. Here is an example of the function:
https://github.com/FirstHeberg/api/blob/master/samples/vps/distrib.php
Does this answer your request?

Regards,
The firstheberg.com team

**Comment by zeko2010ss** [comment]
no sir if I want to install windows server 2008 I will use $system = 'win2k8-trial'; so what if I want install others

**Comment by GuillaumeJeanFrancois** [comment]
Hello,

Okay I close your request then.

Have a good day.
